### ISSUE TITLE
Is it fully async for metrics update and metrics exposure

### ISSUE THREAD

**Issue by stephanecollot** [Llandy3d/pytheus#55]
Hello,

I'm currently using aioprometheus but facing an issue the metrics exposure is blocking my entire FastAPI app https://github.com/claws/aioprometheus/issues/98
Do you think I won't face this issue with Pytheus?

Thank you in advance

**Comment by Llandy3d** [comment]
Hi there,

For a FastAPI application with this lib you should try the rust based backend, it's documented here: https://pythe.us/rust_backend/

With that you just create a normal sync view to expose the metrics and it won't block your application
```python
@app.get('/metrics')
def pytheus_metrics():
    return generate_metrics()
```

**note:** there is an issue in multiprocess applications where a scrape will only get data for the instance it hits, this means it might get a couple of scrapes to update some values, depending on your use case it might be a problem or not
- https://github.com/Llandy3d/pytheus-backend-rs/issues/4

**Comment by Llandy3d** [comment]
Closing this issue as there doesn't seem to be an actionable problem 😄 

The issue with multiprocessing above has been fixed with https://github.com/Llandy3d/pytheus-backend-rs/pull/6
